### ISSUE TITLE
cant deinstall simple nick - no colors - ranks in command-feedback

### ISSUE THREAD

**Issue by ghost** [LakyLuc/SimpleNick#3]
Hello,

I tried SimpleNick but it is not as good as I thought.

The Luckperms Ranks are not displayed correctly. There are no colours in the chat. Animals have ranks. Ranks are displayed in the command feedback.

Please help me! I have a small server network where these errors are a problem! PLEASE HELP! I'm desperate.

Best regards

**Comment by LakyLuc** [comment]
the chat format is defined int the config file (default: '%player% §8> §r%message%')
if you want custom colors by rank, set it to '%player%%message%' and use a suffix in luckperms

the names of the animals are not actually changed
unfortunately, the ranks cannot be removed in the command feedback

to uninstall the plugin you can simply delete the jar file in the plugins folder and restart the server

**Comment by ghost** [comment]
I now understand why the colours with "&" don't work, because you have to use "§".
My parrot had suddenly "&4[OWNER] parrot was killed by &4[OWNER] ______" (Everything white without colours)
Too bad you can't turn it off in the command feedback. :(
I uninstalled it in the plugin folder, but it didn't work. (Was a server error :/)

**Comment by LakyLuc** [comment]
it looks like the parrot is in the same team as the player and i haven't found a way or reason to change that now
